spring:
  application:
    name: tgSqueezer
  config:
    import: optional:/opt/tgSqueezer/config/bot.yaml
  datasource:
    url: jdbc:sqlite:./data/sample.db
    driver-class-name: org.sqlite.JDBC
    jpa:
      hibernate:
        ddl-auto: none
  sql:
    init:
      schema-locations: classpath:schema.sql